### ISSUE TITLE
Compatibility issues running in GLSL 1.10 or lower

### ISSUE THREAD

**Issue by tyanyuy3125** [CodingEric/Erics-MagicaVoxel-Shaders#2]
## Basic Info

**Tested MagicaVoxel Version:** 0.99.2

**GLSL version:** 1.10

**Behavior:** Simply cannot execute

**Target Platform:** Linux wine, macOS and Windows with lower GLSL version.

## Log

_In fact all the shaders in this project cannot avoid the mentioned problem. The log below belongs to the Terrain Generator._

> [Cmd] : xs : tergen 19260817 50 20 1
[Log] cache model
[Log] compute model
==== [GL:Shader] ====
0:19(10): warning: Float suffixes are invalid in GLSL 1.10
0:19(84): warning: Float suffixes are invalid in GLSL 1.10
0:24(75): warning: Float suffixes are invalid in GLSL 1.10
0:25(67): warning: Float suffixes are invalid in GLSL 1.10
0:26(24): warning: Float suffixes are invalid in GLSL 1.10
0:31(31): warning: Float suffixes are invalid in GLSL 1.10
0:49(33): warning: Float suffixes are invalid in GLSL 1.10
0:15(2): error: operator '%' is reserved in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:15(2): error: could not implicitly convert error to int
0:16(2): error: operator '%' is reserved in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:16(2): error: could not implicitly convert error to int
0:18(7): error: bit-wise operations are forbidden in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:18(7): error: bit-wise operations are forbidden in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:18(7): error: type mismatch
0:18(6): error: bit-wise operations are forbidden in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:19(22): error: bit-wise operations are forbidden in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:19(22): error: type mismatch
0:19(16): error: cannot construct \`float' from a non-numeric data type
0:19(16): error: operands to arithmetic operators must be numeric
0:19(10): error: operands to arithmetic operators must be numeric
0:20(9): warning: \`o' used uninitialized
0:31(11): error: could not implicitly convert operands to arithmetic operator
0:31(10): error: operands to arithmetic operators must be numeric
0:32(14): warning: \`f' used uninitialized
0:32(12): error: could not implicitly convert operands to arithmetic operator
0:32(9): error: operands to arithmetic operators must be numeric
0:32(19): warning: \`f' used uninitialized
0:32(9): error: operands to arithmetic operators must be numeric
0:32(2): error: \`return' with wrong type error, in function \`cosini' returning float
0:37(13): error: could not implicitly convert operands to arithmetic operator
0:39(13): error: could not implicitly convert operands to arithmetic operator
0:40(56): warning: \`fraX' used uninitialized
0:41(60): warning: \`fraX' used uninitialized
0:42(22): warning: \`fraY' used uninitialized
0:48(13): error: no matching function for call to \`pow(float, int)'; candidates are:
0:48(13): error:    float pow(float, float)
0:48(13): error:    vec2 pow(vec2, vec2)
0:48(13): error:    vec3 pow(vec3, vec3)
0:48(13): error:    vec4 pow(vec4, vec4)
0:49(16): warning: \`freq' used uninitialized
0:49(23): warning: \`freq' used uninitialized
0:49(29): error: no matching function for call to \`pow(float, int)'; candidates are:
0:49(29): error:    float pow(float, float)
0:49(29): error:    vec2 pow(vec2, vec2)
0:49(29): error:    vec3 pow(vec3, vec3)
0:49(29): error:    vec4 pow(vec4, vec4)
0:49(9): error: operands to arithmetic operators must be numeric
0:49(2): error: operands to arithmetic operators must be numeric
0:49(2): error: could not implicitly convert error to float
0:55(17): error: could not implicitly convert operands to arithmetic operator
0:56(25): warning: \`height' used uninitialized
0:56(44): error: operands of \`==' must have the same type
[Error] cmd failed to parse parms: MV_CMD_VoxelShader

## Fixing status
Now `project` `tergen` `flow` `lifegame` `flow2` `tergen2` `cave` `drop` `cubefill` shaders work in GLSL 1.10.

**Comment by Swivelgames** [comment]
Bummer! I was racking my brain as to why they wouldn't execute.

By the way, how did you get this log? I was trying to find a console output of some kind to see if the scripts were failing, but couldn't find one.

**Comment by capnslipp** [comment]
@Swivelgames I'm also curious where you found MagicaVoxel's logfile.  I'd like to fix some shaders for the latest version of MV, but don't know what it's getting caught up on.

**Comment by tyanyuy3125** [comment]
**To view the logging file:**
* If you are using Wine for Mac, Linux or even WSL, simply launch `MagicaVoxel.exe` with Wine through terminal and Wine itself will print all the debugging logs via terminal, and it's real-time.
* For Windows users, try GLIntercept ( https://github.com/dtrebilco/glintercept ), it generates the shader compiling data right in the `/Shader` directory which is more detailed.

**Comment by capnslipp** [comment]
That makes too much sense.

**For macOS:**
* Open Terminal.app and drag-and-drop MagicaVoxel.app onto the Terminal window… this'll type the path to MagicaVoxel for you, something like `/Applications/MagicaVoxel-0.98.2-mac/MagicaVoxel.app`
* Backspace once to remove the space after the path, and type `/Contents/MacOS/MagicaVoxel`, resulting a command prompt that looks like `$ /Applications/MagicaVoxel-0.98.2-mac/MagicaVoxel.app/Contents/MacOS/MagicaVoxel`.
* Hit enter.  Keep the Terminal window open for as long as MagicaVoxel is running, and the log will show up there.  _(If you close the Terminal window, MagicaVoxel will “force quit” immediately.)_

For long term use, you can create a macOS-friendly bash script _(text file with extension `.command` that has been `chmod +x`-ed)_ and drop it in the same directory as `MagicaVoxel.app`:

`Run MagicaVoxel With Log.command`  
~~~
#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd "$DIR"

./MagicaVoxel.app/Contents/MacOS/MagicaVoxel
~~~

**Comment by tyanyuy3125** [comment]
@capnslipp 
Well done.
I do not use macOS so couldn't provide a solution to it. Your reply is of great help to those macOS users. :)
Thank you.

**Comment by my-little-bunny** [comment]
Hi! 

On my mac I'm getting:

[Cmd] : xs : tergen 19260817 50 20 1 0 -10 10 10
[Log] cache model
[Log] compute model
==== [GL:Shader] ====
ERROR: 0:19: 'f' : syntax error: syntax error

[Error] cmd failed to parse parms: MV_CMD_VoxelShader

And, naturally, shader produces nothing. I'm not a developer, so I don't know if this might help, but I'd very much like to get this shader to work.

**Comment by tyanyuy3125** [comment]
@my-little-bunny 

I have to say that this is a weird issue and it's disappointing that for me locating the bug through the log is nearly impossible.

At present without further investigating I can only guess that the problem comes from the 'f' mark for the float number. I've removed the mark in the latest build, please check it out and see if the problem disappears. If the problem still exists, welcome to comment in this issue.

Hope to help.

**Comment by my-little-bunny** [comment]
Thank you for your reply. Sadly, shader (and all of the others) still doesn't work. New log:

[Log] compute model
==== [GL:Shader] ====
ERROR: 0:18: '<<' does not operate on 'int' and 'int'
ERROR: 0:19: '&' does not operate on 'int' and 'int'
ERROR: 0:20: Use of undeclared identifier 'o'

[Error] cmd failed to parse parms: MV_CMD_VoxelShader

**Comment by my-little-bunny** [comment]
I've copied your command: xs tergen 19260817 50 20 1 0 -10 10 10, so I don't think there were any 'o's.

**Comment by my-little-bunny** [comment]
It may also be worth noting that this shader, xs height, also doesn't work on mac, and ephtracy said it was some sort of problem with mac recognising UTF-8 encoding: https://twitter.com/ephtracy/status/956999681132974082

Although other shaders (https://github.com/lachlanmcdonald/magicavoxel-shaders) work perfectly fine with no problems at all.

**Comment by tyanyuy3125** [comment]
> Thank you for your reply. Sadly, shader (and all of the others) still doesn't work. New log:
> [Log] compute model
> ==== [GL:Shader] ====
> ERROR: 0:18: '<<' does not operate on 'int' and 'int'
> ERROR: 0:19: '&' does not operate on 'int' and 'int'
> ERROR: 0:20: Use of undeclared identifier 'o'
> [Error] cmd failed to parse parms: MV_CMD_VoxelShader

This is actually a compatibility problem now, for the OpenGL in your mac does not support the bitwise-based random generator. To fix it I have to change the algorithm of the generator, which cannot be fixed in a short period of time. I'll manage to do some tests in osx to improve the experience of those users working on non-Windows platforms like you. 

I am so sorry for wasting your precious time. I promise the next release will fix mentioned problems.

**Comment by my-little-bunny** [comment]
Thank you! No need to be sorry, I just wanted to contribute to this issue, sorry I couldn't do more.

**Comment by tyanyuy3125** [comment]
It is worth concerning that the bug of the generator has been fixed at present. Feel free to have a try.

**Comment by my-little-bunny** [comment]
OH MY GOD IT FINALLY WORKS!!!! Thank you so much!!!!

**Comment by tyanyuy3125** [comment]
All fixed. Close the issue.
